/Users/nsmith/Desktop/linglat/Tabulae.jl/quicktest/testtabbuild/latin.a: /Users/nsmith/Desktop/linglat/Tabulae.jl/quicktest/testtabbuild/symbols.fst /Users/nsmith/Desktop/linglat/Tabulae.jl/quicktest/testtabbuild/acceptor.a /Users/nsmith/Desktop/linglat/Tabulae.jl/quicktest/testtabbuild/inflection.a
%.a: %.fst
	/usr/local/bin/fst-compiler-utf8 $< $@
