project:
  type: website
jupyter: julia-1.10  
theme: spacelab
execute:
  freeze: auto
date: last-modified  
margin-header: "⚠️ *These are place-holder pages for documentation of a planned `0.10.0` release of Tabulae.jl.*"

format:
  html: 
    toc: true


website:
  title: "tabulae"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Tutorials"
        file: tutorials/index.qmd          
      - text: "Concepts"
        file: concepts/index.qmd   
      - text: "Guides"
        file: guides/index.qmd           
      - text: "Reference"
        file: reference/index.qmd  
    right:   
      - icon: github
        href: https://github.com/neelsmith/Tabulae.jl
        aria-label: GitHub
      - icon: person-circle
        menu:
          - text: "About me"
            href: https://neelsmith.quarto.pub
          - text: "More of my digital scholarship"
            href: https://neelsmith.quarto.pub/digschol/
        aria-label: "More of my work"
        
  sidebar:
    - title: "Tutorials"
      contents: 
        - tutorials/index.qmd
        - tutorials/parser.qmd
        - tutorials/forms.qmd
        


        
    - title: "Guides"
      contents:
        - guides/index.qmd
        - guides/properties-guide.qmd
        - guides/forms-guide.qmd
        - guides/urns.qmd
        - guides/urnregistry.qmd
    - title: "Reference"
      contents: 
        - reference/index.qmd
        - reference/properties.qmd
        - reference/analytical_types.qmd  
        - reference/file_layout.qmd

    - title: "Concepts"
      contents: 
        - concepts/index.qmd
        - concepts/analysis.qmd
        - concepts/datasets.qmd


        

    - title: "Home"
      contents:
        - index.qmd               
 

           